# This file lists the dependencies needed to build and test all of pyflatsurf.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f environment.yml
# conda env update -n pyflatsurf-build -f environment.yml
name: pyflatsurf-build
channels:
  - flatsurf
  - conda-forge
  - defaults
dependencies:
  - automake
  - cppyy
  - cppyythonizations
  - gmpxxyy
  - libtool
  - make
  - pyexactreal>=1.4.3,<2
  - pytest
  - python
  - setuptools
