# This environment.yml can be used to create a conda environment with
# pyexactreal/libexactreal installed. It is used for our demo binders.
name: binder
channels:
  - flatsurf
  - conda-forge
dependencies:
  - boost-cpp
  - libintervalxt>=3.0.0
  - notebook
  - pyintervalxt>=3.0.0
  - libeantic
  - pyeantic
  - libexactreal
  - pyexactreal
  - xeus-cling
