name: Cancel outdated runs
on:
  workflow_run:
    workflows: ['Test', 'Code Lint', 'Publish to Anaconda', 'Code Coverage' ]
    types: ['requested']

jobs:
  cancel-duplicate-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: potiuk/cancel-workflow-runs@master
        with:
          cancelMode: duplicates
          cancelFutureDuplicates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          sourceRunId: ${{ github.event.workflow_run.id }}
          skipEventTypes: '["push", "schedule"]'
